name: yuko2022
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy=1.23.5
  - pandas=1.5.2
  - pip=22.3.1
  - python=3.9.15
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.1
  - selenium=4.2.0
  - beautifulsoup4
  - pip:
    - docopt-ng==0.8.1
    - joblib==1.1.0
    - lxml==4.9.2
    - vl-convert-python==0.5.0
