name: 'yuko2022'
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - ipykernel
  - ipython>=7.15
  - scikit-learn>=1.1.3
  - altair_saver
  - selenium<4.3.0
  - pip
  - pip:
    - joblib==1.1.0
